Use actions/checkout@v2 instead but specify fetch-depth
To fix the following error:

    Run git push ***git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
      git push ***git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
      shell: /bin/bash -e {0}
      env:
        HEROKU_API_TOKEN: ***
        HEROKU_APP_NAME: ka-nodejs-express-markdown
    To https://git.heroku.com/ka-nodejs-express-markdown.git
     ! [rejected]        origin/master -> master (fetch first)
    error: failed to push some refs to '***git.heroku.com/ka-nodejs-express-markdown.git'
    hint: Updates were rejected because the remote contains work that you do
    hint: not have locally. This is usually caused by another repository pushing
    hint: to the same ref. You may want to first integrate the remote changes
    hint: (e.g., 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    ##[error]Process completed with exit code 1.

ref. https://github.com/kaosf/nodejs-express-markdown/runs/540254032?check_suite_focus=true